server:
  port: 8088
  servlet:
    context-path: /
  
#JPA
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
#数据源
  datasource:
    url: jdbc:mysql://localhost:3306/event?serverTimezone=GMT%2B8 & useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    
#Thymeleaf
  thymeleaf:
    cach: false #测试开发时没必要开启缓存
    mode: LEGACYHTML5 #解决html5标签不全的情况（必须导入nekohtml库文件）
    encoding: UTF-8

    